# Generated by Django 3.2.6 on 2021-10-11 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['created_at'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
    ]
