# Generated by Django 3.2.6 on 2021-10-11 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-modified_at'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
    ]
